### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by VJ1224** [VJ1224/art-gallery#2]
- [x] Add search artwork
- [x] Add artwork totals by category
- [x] Checkout form
- [x] Update artist select tag
- [x] Update password
